apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: 3940ass4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3940ass4
  template:
    metadata:
      labels:
        app: 3940ass4
    spec:
      containers:
      - name: 3940ass4
        image: ryanwo3/csass4
        ports:
        - containerPort: 9000

--- 
apiVersion: v1
kind: Service
metadata:
  name: router
  labels: 
   app: 3940ass4
spec:
  selector:
    app: 3940ass4 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8999 
      targetPort: 9000
      nodePort: 30001
